### ISSUE TITLE
"In channel lightViewProjection has no input" when using ShadowTextureMaterial

### ISSUE THREAD

**Issue by thomas-zahner** [philipp-kramer/SharpGfx#3]
When using `ShadowTextureMaterial` occasionally the following exception is thrown:

Unhandled exception. System.InvalidOperationException: In channel lightViewProjection has no input
   at SharpGfx.OpenGL.Shading.OpenGlMaterial.CheckInputs()
   at SharpGfx.OpenTK.OtkRenderer.Render(IEnumerable`1 scene, IVector2 pixels, Color4 ambientColor)
   at SharpGfx.OpenTK.OtkDevice.Render(ICollection`1 scene, IVector2 pixels, Point3 cameraPosition, Color4 ambientColor)
   at SharpGfx.CameraRendering.OnRenderFrame()
   at SharpGfx.Window.OnRenderFrame()
   at SharpGfx.OpenTK.OtkWindow.OnRenderFrame(FrameEventArgs e)
   at OpenTK.Windowing.Desktop.GameWindow.OnRenderFrame(FrameEventArgs args)
   at OpenTK.Windowing.Desktop.GameWindow.DispatchRenderFrame()
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at SharpGfx.OpenTK.OtkWindow.Show(Rendering rendering)
   at S2A2.Program.Main() in Program.cs:line 19

With [this commit](https://github.com/philipp-kramer/SharpGfx/commit/9308755574fe8f3bec035ccc7b84445f23780317#diff-d63ddb8e9156820137c967e32fc794d0153c2863756e0c3f2ac10c9c71b57972L32) `lightViewProjection` is no longer set in the constructor but only in the function `Update`. So I assume that `Update` is not guaranteed to be executed before the Shader is loaded or run which causes the exception.

**Comment by philipp-kramer** [comment]
You have to call the Update() method on ShadowTextureMaterial in the OnUpdateFrame() method of your rendering. This change was necessary to correctly update the shadows due to changing light position, i.e. lightViewProjection changes when the light position changes and therefore can't be performed in the constructor when the light moves. When the light does not move, Update() can alternatively be called also in the constructor.
